#!/bin/bash

# database structure
# As a key-value csv: 1 key,value per line
# Only restriction is that keys cannot contain `,`

# default DB file
DB="db1"

function get {
  KEY=$1

  grep "^$KEY" $DB | cut -d, -f2-
}

function put {
  KEY=$1
  VALUE=$2

  sed -ri "s/^$KEY.*/$KEY,$VALUE/" $DB
}

if [ $1 == "get" ]; then
  get $2
elif [[ $1 == "put" ]]; then
  put $2 $3
fi
