#!/bin/bash

# database structure
# As a key-value csv: 1 key,value per line
# Only restriction is that keys cannot contain `,`

# default DB file
DB="db1"

function get {
  KEY=$1

  grep "^$KEY" $DB | cut -d, -f2-
}

function put {
  KEY=$1
  VALUE=$2

  if [[ $(get $KEY) == "" ]]; then
    # insert key
    echo "$KEY,$VALUE" >> $DB
  else
    # update key
    sed -ri "s/^$KEY.*/$KEY,$VALUE/" $DB
  fi
}

if [ $1 == "get" ]; then
  get $2
elif [[ $1 == "put" ]]; then
  put $2 $3
fi
